import { PrismaClient } from '@prisma/client';
import { parseArgs } from 'node:util';
const prisma = new PrismaClient();

const options = {
  environment: { type: 'string' } as const,
};

async function main() {
  const {
    values: { environment },
  } = parseArgs({ options });

  switch (environment) {
    case 'development':
      /** Seedind countries */
      await prisma.country.createMany({
        data: [
          { name: 'Afghanistan', code: 'AF' },
          { name: 'Albania', code: 'AL' },
          { name: 'Algeria', code: 'DZ' },
          { name: 'Andorra', code: 'AD' },
          { name: 'Angola', code: 'AO' },
          { name: 'Antigua and Barbuda', code: 'AG' },
          { name: 'Argentina', code: 'AR' },
          { name: 'Armenia', code: 'AM' },
          { name: 'Australia', code: 'AU' },
          { name: 'Austria', code: 'AT' },
          { name: 'Azerbaijan', code: 'AZ' },
          { name: 'Bahamas', code: 'BS' },
          { name: 'Bahrain', code: 'BH' },
          { name: 'Bangladesh', code: 'BD' },
          { name: 'Barbados', code: 'BB' },
          { name: 'Belarus', code: 'BY' },
          { name: 'Belgium', code: 'BE' },
          { name: 'Belize', code: 'BZ' },
          { name: 'Benin', code: 'BJ' },
          { name: 'Bhutan', code: 'BT' },
          { name: 'Bolivia', code: 'BO' },
          { name: 'Bosnia and Herzegovina', code: 'BA' },
          { name: 'Botswana', code: 'BW' },
          { name: 'Brazil', code: 'BR' },
          { name: 'Brunei Darussalam', code: 'BN' },
          { name: 'Bulgaria', code: 'BG' },
          { name: 'Burkina Faso', code: 'BF' },
          { name: 'Burundi', code: 'BI' },
          { name: 'Cambodia', code: 'KH' },
          { name: 'Cameroon', code: 'CM' },
          { name: 'Canada', code: 'CA' },
          { name: 'Cape Verde', code: 'CV' },
          { name: 'Central African Republic', code: 'CF' },
          { name: 'Chad', code: 'TD' },
          { name: 'Chile', code: 'CL' },
          { name: 'China', code: 'CN' },
          { name: 'Colombia', code: 'CO' },
          { name: 'Comoros', code: 'KM' },
          { name: 'Congo', code: 'CG' },
          { name: 'Costa Rica', code: 'CR' },
          { name: 'Croatia', code: 'HR' },
          { name: 'Cuba', code: 'CU' },
          { name: 'Cyprus', code: 'CY' },
          { name: 'Czech Republic', code: 'CZ' },
          { name: 'Democratic Republic of the Congo', code: 'CD' },
          { name: 'Denmark', code: 'DK' },
          { name: 'Djibouti', code: 'DJ' },
          { name: 'Dominica', code: 'DM' },
          { name: 'Dominican Republic', code: 'DO' },
          { name: 'Ecuador', code: 'EC' },
          { name: 'Egypt', code: 'EG' },
          { name: 'El Salvador', code: 'SV' },
          { name: 'Equatorial Guinea', code: 'GQ' },
          { name: 'Eritrea', code: 'ER' },
          { name: 'Estonia', code: 'EE' },
          { name: 'Eswatini', code: 'SZ' },
          { name: 'Ethiopia', code: 'ET' },
          { name: 'Fiji', code: 'FJ' },
          { name: 'Finland', code: 'FI' },
          { name: 'France', code: 'FR' },
          { name: 'Gabon', code: 'GA' },
          { name: 'Gambia', code: 'GM' },
          { name: 'Germany', code: 'DE' },
          { name: 'Ghana', code: 'GH' },
          { name: 'Greece', code: 'GR' },
          { name: 'Grenada', code: 'GD' },
          { name: 'Guatemala', code: 'GT' },
          { name: 'Guinea', code: 'GN' },
          { name: 'Guinea-Bissau', code: 'GW' },
          { name: 'Guyana', code: 'GY' },
          { name: 'Haiti', code: 'HT' },
          { name: 'Honduras', code: 'HN' },
          { name: 'Hungary', code: 'HU' },
          { name: 'Iceland', code: 'IS' },
          { name: 'India', code: 'IN' },
          { name: 'Indonesia', code: 'ID' },
          { name: 'Iran', code: 'IR' },
          { name: 'Iraq', code: 'IR' },
          { name: 'Ireland', code: 'IE' },
          { name: 'Israel', code: 'IL' },
          { name: 'Italy', code: 'IT' },
          { name: 'Jamaica', code: 'JM' },
          { name: 'Japan', code: 'JP' },
          { name: 'Jordan', code: 'JO' },
          { name: 'Kazakhstan', code: 'KZ' },
          { name: 'Kenya', code: 'KE' },
          { name: 'Kiribati', code: 'KI' },
          { name: 'Korea (North)', code: 'KP' },
          { name: 'Korea (South)', code: 'KR' },
          { name: 'Kuwait', code: 'KW' },
          { name: 'Kyrgyzstan', code: 'KG' },
          { name: 'Laos', code: 'LA' },
          { name: 'Latvia', code: 'LV' },
          { name: 'Lebanon', code: 'LB' },
          { name: 'Lesotho', code: 'LS' },
          { name: 'Liberia', code: 'LR' },
          { name: 'Libya', code: 'LY' },
          { name: 'Liechtenstein', code: 'LI' },
          { name: 'Lithuania', code: 'LT' },
          { name: 'Luxembourg', code: 'LU' },
          { name: 'Madagascar', code: 'MG' },
          { name: 'Malawi', code: 'MW' },
          { name: 'Malaysia', code: 'MY' },
          { name: 'Maldives', code: 'MV' },
          { name: 'Mali', code: 'ML' },
          { name: 'Malta', code: 'MT' },
          { name: 'Marshall Islands', code: 'MH' },
          { name: 'Mauritania', code: 'MR' },
          { name: 'Mauritius', code: 'MU' },
          { name: 'Mexico', code: 'MX' },
          { name: 'Micronesia', code: 'FM' },
          { name: 'Moldova', code: 'MD' },
          { name: 'Monaco', code: 'MC' },
          { name: 'Mongolia', code: 'ME' },
          { name: 'Montenegro', code: 'CGO' },
          { name: 'Morocco', code: 'MA' },
          { name: 'Mozambique', code: 'MZ' },
          { name: 'Myanmar', code: 'MM' },
          { name: 'Namibia', code: 'NA' },
          { name: 'Nauru', code: 'NR' },
          { name: 'Nepal', code: 'NP' },
          { name: 'Netherlands', code: 'NL' },
          { name: 'New Zealand', code: 'NZ' },
          { name: 'Nicaragua', code: 'NI' },
          { name: 'Niger', code: 'NE' },
          { name: 'Nigeria', code: 'NG' },
          { name: 'North Macedonia', code: 'MK' },
          { name: 'Norway', code: 'NO' },
          { name: 'Oman', code: 'OM' },
          { name: 'Pakistan', code: 'PK' },
          { name: 'Palau', code: 'PW' },
          { name: 'Panama', code: 'PQ' },
          { name: 'Papua New Guinea', code: 'PG' },
          { name: 'Paraguay', code: 'PY' },
          { name: 'Peru', code: 'PE' },
          { name: 'Philippines', code: 'PH' },
          { name: 'Poland', code: 'PL' },
          { name: 'Portugal', code: 'PT' },
          { name: 'Qatar', code: 'QA' },
          { name: 'Romania', code: 'RO' },
          { name: 'Russia', code: 'RU' },
          { name: 'Rwanda', code: 'RW' },
          { name: 'Saint Kitts and Nevis', code: 'KN' },
          { name: 'Saint Lucia', code: 'LC' },
          { name: 'Saint Vincent and the Grenadines', code: 'VC' },
          { name: 'Samoa', code: 'WS' },
          { name: 'San Marino', code: 'CGO' },
          { name: 'Sao Tome and Principe', code: 'ST' },
          { name: 'Saudi Arabia', code: 'SA' },
          { name: 'Senegal', code: 'SN' },
          { name: 'Serbia', code: 'RS' },
          { name: 'Seychelles', code: 'SC' },
          { name: 'Sierra Leone', code: 'SG' },
          { name: 'Singapore', code: 'SG' },
          { name: 'Slovakia', code: 'SK' },
          { name: 'Slovenia', code: 'SI' },
          { name: 'Solomon Islands', code: 'SB' },
          { name: 'Somalia', code: 'SO' },
          { name: 'South Africa', code: 'ZA' },
          { name: 'South Sudan', code: 'SS' },
          { name: 'Spain', code: 'ES' },
          { name: 'Sri Lanka', code: 'LK' },
          { name: 'Sudan', code: 'SD' },
          { name: 'Suriname', code: 'SR' },
          { name: 'Sweden', code: 'SE' },
          { name: 'Switzerland', code: 'CH' },
          { name: 'Syria', code: 'SY' },
          { name: 'Taiwan', code: 'TW' },
          { name: 'Tajikistan', code: 'TJ' },
          { name: 'Tanzania', code: 'TZ' },
          { name: 'Thailand', code: 'TH' },
          { name: 'Timor-Leste', code: 'TL' },
          { name: 'Togo', code: 'TG' },
          { name: 'Tonga', code: 'TO' },
          { name: 'Trinidad and Tobago', code: 'IT' },
          { name: 'Tunisia', code: 'TN' },
          { name: 'Turkey', code: 'TR' },
          { name: 'Turkmenistan', code: 'TM' },
          { name: 'Tuvalu', code: 'TV' },
          { name: 'Uganda', code: 'UG' },
          { name: 'Ukraine', code: 'UA' },
          { name: 'United Arab Emirates', code: 'AE' },
          { name: 'United Kingdom', code: 'GB' },
          { name: 'United States', code: 'US' },
          { name: 'Uruguay', code: 'UY' },
          { name: 'Uzbekistan', code: 'UZ' },
          { name: 'Vanuatu', code: 'VU' },
          { name: 'Vatican City', code: 'VA' },
          { name: 'Venezuela', code: 'VE' },
          { name: 'Vietnam', code: 'VN' },
          { name: 'Yemen', code: 'YE' },
          { name: 'Zambia', code: 'ZM' },
          { name: 'Zimbabwe', code: 'ZW' },
        ],
      });

      /** Seedind currencies */
      await prisma.currency.createMany({
        data: [
          { name: 'Algerian Dinar', code: 'DZD', symbol: 'د.ج' },
          { name: 'Angolan Kwanza', code: 'AOA', symbol: 'Kz' },
          { name: 'Botswana Pula', code: 'BWP', symbol: 'P' },
          { name: 'Burundian Franc', code: 'BIF', symbol: 'FBu' },
          { name: 'Cape Verdean Escudo', code: 'CVE', symbol: 'Esc' },
          { name: 'Central African CFA Franc', code: 'XAF', symbol: 'FCFA' },
          { name: 'Comorian Franc', code: 'KMF', symbol: 'CF' },
          { name: 'Congolese Franc', code: 'CDF', symbol: 'FC' },
          { name: 'Djiboutian Franc', code: 'DJF', symbol: 'Fdj' },
          { name: 'Egyptian Pound', code: 'IQD', symbol: 'E£' },
          { name: 'Eritrean Nakfa', code: 'ERN', symbol: 'Nfk' },
          { name: 'Ethiopian Birr', code: 'ETB', symbol: 'Br' },
          { name: 'Gambian Dalasi', code: 'GMD', symbol: 'D' },
          { name: 'Ghanaian Cedi', code: 'GHS', symbol: 'GH₵' },
          { name: 'Guinean Franc', code: 'GNF', symbol: 'FG' },
          { name: 'Kenyan Shilling', code: 'KES', symbol: 'KSh' },
          { name: 'Lesotho Loti', code: 'LSL', symbol: 'L' },
          { name: 'Liberian Dollar', code: 'LRD', symbol: 'L$' },
          { name: 'Libyan Dinar', code: 'LYD', symbol: 'LD' },
          { name: 'Malagasy Ariary', code: 'MGA', symbol: 'Ar' },
          { name: 'Malawian Kwacha', code: 'MWK', symbol: 'MK' },
          { name: 'Mauritanian Ouguiya', code: 'MRU', symbol: 'UM' },
          { name: 'Mauritian Rupee', code: 'MUR', symbol: 'Rs' },
          { name: 'Moroccan Dirham', code: 'MAD', symbol: 'د.م.' },
          { name: 'Mozambican Metical', code: 'MZN', symbol: 'MT' },
          { name: 'Namibian Dollar', code: 'NAD', symbol: 'N$' },
          { name: 'Nigerian Naira', code: 'NGN', symbol: '₦' },
          { name: 'Rwandan Franc', code: 'RWF', symbol: 'FRw' },
          { name: 'São Tomé and Príncipe Dobra', code: 'STN', symbol: 'Db' },
          { name: 'West African CFA Franc', code: 'XOF', symbol: 'CFA' },
          { name: 'Seychellois Rupee', code: 'SCR', symbol: 'Rs' },
          { name: 'Sierra Leonean Leone', code: 'SLL', symbol: 'Le' },
          { name: 'Somali Shilling', code: 'SOS', symbol: 'Sh' },
          { name: 'South African Rand', code: 'ZAR', symbol: 'R' },
          { name: 'South Sudanese Pound', code: 'SSP', symbol: 'SSP' },
          { name: 'Sudanese Pound', code: 'SDG', symbol: 'SDG' },
          { name: 'Swazi Lilangeni', code: 'SZL', symbol: 'E' },
          { name: 'Tanzanian Shilling', code: 'TZS', symbol: 'TSh' },
          { name: 'Tunisian Dinar', code: 'TND', symbol: 'د.ت' },
          { name: 'Ugandan Shilling', code: 'UGX', symbol: 'USh' },
          { name: 'Zambian Kwacha', code: 'ZMW', symbol: 'ZK' },
          { name: 'Zimbabwean Dollar', code: 'ZWL', symbol: 'Z$' },
          { name: 'United States Dollar', code: 'USD', symbol: '$' },
          { name: 'Euro', code: 'EUR', symbol: '€' },
          { name: 'Japanese Yen', code: 'JPY', symbol: '¥' },
          { name: 'British Pound Sterling', code: 'GBP', symbol: '£' },
          { name: 'Swiss Franc', code: 'CHF', symbol: 'CHF' },
          { name: 'Canadian Dollar', code: 'CAD', symbol: 'CA$' },
          { name: 'Australian Dollar', code: 'AUD', symbol: 'A$' },
          { name: 'Chinese Yuan (Renminbi)', code: 'CNY', symbol: '¥' },
          { name: 'Swedish Krona', code: 'SEK', symbol: 'kr' },
          { name: 'New Zealand Dollar', code: 'NZD', symbol: 'NZ$' },
          { name: 'South Korean Won', code: 'KRW', symbol: '₩' },
          { name: 'Singapore Dollar', code: 'SGD', symbol: 'S$' },
          { name: 'Hong Kong Dollar', code: 'HKD', symbol: 'HK$' },
          { name: 'Norwegian Krone', code: 'NOK', symbol: 'kr' },
          { name: 'Mexican Peso', code: 'MXN', symbol: 'Mex$' },
          { name: 'Indian Rupee', code: 'INR', symbol: '₹' },
          { name: 'Russian Ruble', code: 'RUB', symbol: '₽' },
          { name: 'Brazilian Real', code: 'BRL', symbol: 'R$' },
          { name: 'South African Rand', code: 'ZAR', symbol: 'R' },
          { name: 'Turkish Lira', code: 'TRY', symbol: '₺' },
          { name: 'UAE Dirham', code: 'AED', symbol: 'د.إ' },
          { name: 'Saudi Riyal', code: 'SAR', symbol: 'ر.س' },
          { name: 'Thai Baht', code: 'THB', symbol: '฿' },
          { name: 'Israeli New Shekel', code: 'ILS', symbol: '₪' },
          { name: 'Indonesian Rupiah', code: 'IDR', symbol: 'Rp' },
          { name: 'Malaysian Ringgit', code: 'MYR', symbol: 'RM' },
          { name: 'Philippine Peso', code: 'PHP', symbol: '₱' },
          { name: 'Pakistani Rupee', code: 'PKR', symbol: 'Rs' },
          { name: 'Argentine Peso', code: 'ARS', symbol: '$' },
          { name: 'Collombian Peso', code: 'COP', symbol: '$' },
          { name: 'Chilean Peso', code: 'CLP', symbol: '$' },
          { name: 'Ukrainian Hryvnia', code: 'UAH', symbol: '₴' },
          { name: 'Vietnamese Dong', code: 'VND', symbol: '₫' },
          { name: 'Bangladeshi Taka', code: 'BDT', symbol: '৳' },
          { name: 'Peruvian Sol', code: 'PEN', symbol: 'S/.' },
          { name: 'Kuwaiti Dinar', code: 'KWD', symbol: 'د.ك' },
          { name: 'Qatar Riyal', code: 'QAR', symbol: 'ر.ق' },
          { name: 'Omani Rial', code: 'OMR', symbol: 'ر.ع.' },
          { name: 'Jordanian Dinar', code: 'JOD', symbol: 'د.ا' },
          { name: 'Bahraini Dinar', code: 'BHD', symbol: 'د.ب' },
          { name: 'Icelandic Krona', code: 'ISK', symbol: 'kr' },
          { name: 'Iraqi Dinar', code: 'IQD', symbol: 'د.ع' },
          { name: 'Lebanese Pound', code: 'LBP', symbol: 'ل.ل' },
          { name: 'Sri Lankan Rupee', code: 'LKR', symbol: 'Rs' },
          { name: 'Georgian Lari', code: 'GEL', symbol: '₾' },
          { name: 'Costa Rican Colon', code: 'CRC', symbol: '₡' },
          { name: 'Croatian Kuna', code: 'HRK', symbol: 'kn' },
          { name: 'Bulgarian Lev', code: 'BGN', symbol: 'лв' },
          { name: 'Romanian Leu', code: 'RON', symbol: 'lei' },
          { name: 'Czech Koruna', code: 'CZK', symbol: 'Kč' },
          { name: 'Danish Krone', code: 'DKK', symbol: 'kr' },
          { name: 'Hungarian Forint', code: 'HUF', symbol: 'Ft' },
          { name: 'Polish Zloty', code: 'PLN', symbol: 'zł' },
        ],
      });

      /** Seeding animal types */
      await prisma.animalType.createMany({
        data: [
          {
            name: 'Poulet de chair',
            slug: 'poulets de chair',
            habitat: 'poulaillé',
            description:
              'Ici vous pouvez élever des poulets de chaire zero jour à 31jour puis les vendre pour la viande',
          },
          {
            name: 'Pondeuses',
            slug: 'pondeuses',
            habitat: 'poulaillé',
            description:
              'Ici vous pouvez élever des pousins jusqua la phase de ponte pour les oeufs et puis les reformer pour la viande',
          },
          {
            name: 'Bovins',
            slug: 'boeufs',
            habitat: 'Etable',
            description:
              'Une section pour élever des boeuf pour leur viande et du lait.',
          },
          {
            name: 'Ovins',
            slug: 'moutons',
            habitat: 'enclos',
            description: 'Elever des moutons pour leur viande ou de laine',
          },
          {
            name: 'Caprins',
            slug: 'chèvres',
            habitat: 'enclos',
            description: 'Elever des chèvres pour leurs viande ou du lait',
          },
          {
            name: 'Porciculture',
            slug: 'porcs',
            habitat: 'loge',
            description:
              'Elever des porcs pour leur viande bien grasse qui passe sur le marché nhesitez pas a varier les races',
          },
          {
            name: 'Cuniculture',
            slug: 'lapins',
            habitat: 'clapier',
            description:
              'Elever des lapins pour leur viande succulent faible en matière grasse et bonne pour la santé',
          },
          {
            name: 'Quails',
            slug: 'quails',
            habitat: 'cage',
            description:
              'Elever des quails pour les viande et leur oeufs faible en matière grasse et veture médicinale',
          },
          {
            name: 'Canard',
            slug: 'canards',
            habitat: 'canardière',
            description:
              'Elever des canard pour leur rusticité leur viande et leur oeufs.',
          },
          {
            name: 'Pisciculture',
            slug: 'poissons',
            habitat: 'etang',
            description:
              'Elever des poissons pour la consomation domestique ou la vente',
          },
          {
            name: 'Dinde',
            slug: 'dindons',
            habitat: 'poulaillé',
            description:
              'Elever des dindons et des dindes pour leur bonne viande blanche très riche en proteins et vente en grande surface',
          },
          {
            name: 'Pintarde',
            slug: 'pintardes',
            habitat: 'poullaillé',
            description:
              'Elever des pintarde pour leur rusticité et la vente de leur bonne viande blanche très faible en matière grasse, riche en proteins',
          },
          {
            name: 'Poulets Brahma',
            slug: 'poulets brahma',
            habitat: 'poullaillé',
            description:
              'Elever des pintarde pour leur rusticité et la vente de leur bonne viande blanche très faible en matière grasse, riche en proteins',
          },
          {
            name: 'Poulets Goliaths',
            slug: 'poulets goliath',
            habitat: 'poullaillé',
            description:
              'Elever des pintarde pour leur rusticité et la vente de leur bonne viande blanche très faible en matière grasse, riche en proteins',
          },
        ],
      });
      console.log(`${environment} database seeded successfully`);
      break;
    case 'test':
      /** data for your test environment */
      break;
    default:
      break;
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
